import Sidebar from "@/components/Shared/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex  h-screen w-auto  flex-row   justify-start overflow-hidden p-0 relative">
          <Sidebar />
          <main className=" p-2  pl-0  flex-1 flex flex-col rounded-lg bg-main  relative  will-change-transform justify-start h-screen w-[1px]">
            <div className=" bg-main-border"></div>
            <div className="flex-1 flex flex-col justify-start relative p-4 sm:p-8 gap-8  overflow-hidden overflow-y-auto w-full  will-change-transform h-[1px] flex-nowrap">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
